### ISSUE TITLE
Client : lost jquery-minicolors.js in org.openwms.client.angularjs.app

### ISSUE THREAD

**Issue by huyouzhong** [openwms/org.openwms#147]
when i want to run index.html in org.openwms.client.angularjs.app, it shows error : 

require.js:1903 GET file:///E:/org.openwms-master/org.openwms.app/org.openwms.client.angularjs.app/src/main/ajs/app/scripts/jquery-minicolors.js net::ERR_FILE_NOT_FOUND

and I really can't find jquery-minicolors.js file in scripts file

**Comment by openwms** [comment]
Do you refer to master?

those files are downloaded by bower to the folder bower_components
inf [index.html](https://github.com/openwms/org.openwms/blob/master/org.openwms.app/org.openwms.client.angularjs.app/src/main/ajs/app/index.html) those are referenced in bower_components too:
```
<link rel="stylesheet" href="bower_components/jquery-minicolors/jquery.minicolors.css">
```

**Comment by huyouzhong** [comment]
thank you for your response~

I'm in master branch, all bower components are downloaded, including jquery-minicolors package,  the lost file name is jquery-minicolors.js , not jquery.minicolor.js, and seems it should be in folder ajs/app/scripts/.

the error shows as below:
![wms_index_error](https://cloud.githubusercontent.com/assets/5310794/23787180/c397363e-05ab-11e7-9d13-d30b96300e9b.png)

**Comment by huyouzhong** [comment]
thank you for your response~

I'm in master branch, all bower components are downloaded, including jquery-minicolors package, the lost file name is jquery-minicolors.js , not jquery.minicolor.js, and seems it should be in folder ajs/app/scripts/.

the error shows as below:
![wmsindexerror](https://cloud.githubusercontent.com/assets/5310794/23787270/33ebc616-05ac-11e7-817b-f361e6552ecd.png)

**Comment by openwms** [comment]
Looks like the minified version of jquery-minicolors is not available anymore. Please checkout PR #149
