### ISSUE TITLE
Start the Application

### ISSUE THREAD

**Issue by andreaeasycloud** [openwms/org.openwms#153]
Hello,
are there istructions to correctly start the application?
... java -jar......  ....
and then
go to http://localhost:8080/.....   ?

Also Have I to create a Postgresql  Database? Where can I set the parameters of the database for the application?

![Selection_173](https://user-images.githubusercontent.com/48676861/55945763-b924a580-5c4b-11e9-9e0d-66684de9c9fd.png)

What are the minimum resources for a server that hosts this application?

Thank you very much.
Andrea

**Comment by openwms** [comment]
An application consists of several microservices. At least you need to have the service registry and the configuration server running. Then you can start the common-service and perhaps the transportation and routing service (for automatic warehouses)
- Service Registry: https://github.com/spring-labs/org.openwms.services
- Configuration Server: https://github.com/spring-labs/org.openwms.configuration
- Common Service: https://github.com/openwms/org.openwms.common.service
